---
name: Development Environment
on:
  schedule:
      - cron: '0 0 * * *'
  push:
    branches:
      - main
    paths:
      - '.github/workflows/devenv.yml'
      - 'devenv/**'
  pull_request:
    paths:
      - '.github/workflows/devenv.yml'
      - 'devenv/**'
  workflow_dispatch:

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}
jobs:
  docker-build:
    name: Docker Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Determine if we should push changes and which tags to use
        run: |
          if [ -n "${{ secrets.DOCKER_USERNAME }}" ] && [ -n "${{ secrets.DOCKER_TOKEN }}" ] && [ "${{ github.event_name }}" != "pull_request" ] ; then
            echo "publish=true" >> $GITHUB_ENV
          else
            echo "publish=false" >> $GITHUB_ENV
          fi
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v2
      - name: Setup Buildx
        uses: docker/setup-buildx-action@v2
      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Prepare Cache
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-devenv
      - name: Docker Build
        uses: docker/build-push-action@v4
        with:
          file: devenv/Dockerfile
          context: devenv
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          push: ${{ env.publish }}
          tags: netbpf/devenv:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new
      - name: Cleanup Cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
